sudo: required

language: node

services:
  - docker

install:
  - docker --version  # document the version travis is using
  - docker build -t docker-pimatic .

script:
  - docker run docker-pimatic
#after_success:

