sudo: required

language: node

services:
  - docker

install:
  - docker --version  # document the version travis is using
  - docker build -t docker-pimatic .

script:
  - docker run --rm --name pimatic-container docker-pimatic
  - timeout 300s docker logs pimatic-container -f
#after_success:

