sudo: required

language: node

services:
  - docker

install:
  - docker --version  # document the version travis is using
  - docker build -t docker-pimatic .
  - docker run -d -p 127.0.0.1:8282:8282 --name docker-pimatic docker-pimatic

script:  
  - docker ps -a
  - wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 15 -O/dev/null localhost:8282
  - docker logs docker-pimatic
#after_success:

