sudo: required

language: node

services:
  - docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

after_success:
  - docker --version  # document the version travis is using
  - docker build -t docker-pimatic .
