sudo: required

language: node

services:
  - docker

install:
  - docker --version  # document the version travis is using
  - docker build -t docker-pimatic .
  - docker run -d -p 127.0.0.1:8282:8282 --name docker-pimatic docker-pimatic

script:  
  - docker ps -a
  - timeout 30s docker logs docker-pimatic -f
  - curl -sSf http://localhost:8282 > /dev/null

#after_success:

