sudo: required

services:
- docker

install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset -p yes
  - docker build -t docker-pimatic-rpi .

script:
  - docker run --rm docker-pimatic-rpi nodejs -v
#after_success:
